version: 2.1

references:
  circleci: &circleci trussworks/circleci:29ab89fdada1f85c5d8fb685a2c71660f0c5f60c

jobs:
  test:
    docker:
      - image: *circleci
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run: make test
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - "~/.cache/pre-commit"

workflows:
  version: 2.1
  validate:
    jobs:
      - test
